// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(grunt) {
    var cssFiles;

    cssFiles = ['public/css/*.css', 'public/css/utils/*.css', '!public/css/background-img.css', 'public/css/vendor/*.css'];
    grunt.initConfig({
      pkg: grunt.file.readJSON('package.json'),
      cssmin: {
        options: {
          expand: true,
          banner: '/*! <%= pkg.name %> <%= grunt.template.today("dd-mm-yyyy")%> */\n'
        },
        combine: {
          files: {
            'build/css/main.min.css': cssFiles
          }
        }
      }
    });
    grunt.loadNpmTasks('grunt-contrib-cssmin');
    grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.registerTask('buildcss', ['cssmin']);
    grunt.registerTask('buildjs', ['uglify']);
    return grunt.registerTask('default', ['cssmin']);
  };

}).call(this);
