// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(grunt) {
    var coffeeFiles, cssFiles, htmlFiles, jsFiles, lessFiles;

    cssFiles = ['public/css/*.css', '!public/css/utils/*.css', '!public/css/vendor/*.css', '!public/css/inherit/*.css'];
    cssFiles = ['public/css/main.css'];
    lessFiles = ['public/less/*.less', 'public/less/utils/*.less', '!public/less/vendor'];
    htmlFiles = ['sm_build/*.html'];
    jsFiles = ['public/js/main.js'];
    coffeeFiles = ['public/coffeescript/*', '/Gruntfile.coffee', 'casperjs_server/app.coffee'];
    grunt.initConfig({
      pkg: grunt.file.readJSON('package.json'),
      cssmin: {
        options: {
          expand: true,
          banner: '/*! <%= pkg.name %> \n CSS Baked on <%= grunt.template.today("dddd, mmmm dS, yyyy, h:MM:ss TT") %> */\n'
        },
        combine: {
          files: {
            'sm_build/css/main.min.css': cssFiles
          }
        }
      },
      uglify: {
        options: {
          banner: '/*! <%= pkg.name %> \n JS Baked on <%= grunt.template.today("dddd, mmmm dS, yyyy, h:MM:ss TT") %> */\n\n'
        },
        my_target: {
          files: {
            'sm_build/js/main.min.js': jsFiles
          }
        }
      },
      coffee_build: {
        options: {
          wrap: true
        },
        files: coffeeFiles
      },
      less: {
        options: {
          paths: ['public/css']
        },
        'public/css/main.css': lessFiles
      },
      watch: {
        cssChanges: {
          files: [cssFiles],
          tasks: ['cssmin'],
          options: {
            livereload: true
          }
        },
        lessChanges: {
          files: [lessFiles],
          tasks: ['less']
        },
        jsChanges: {
          files: [jsFiles, coffeeFiles],
          tasks: ['uglify', 'coffee_build']
        },
        markupChanges: {
          files: [htmlFiles],
          options: {
            livereload: true
          }
        }
      }
    });
    grunt.event.on('watch', function(action, path, target) {
      return grunt.log.writeln(target + ' : ' + path + ' has been ' + action);
    });
    grunt.loadNpmTasks('grunt-contrib-cssmin');
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.loadNpmTasks('grunt-coffee-build');
    grunt.loadNpmTasks('grunt-contrib-less');
    grunt.registerTask('buildcss', ['cssmin']);
    grunt.registerTask('buildjs', ['uglify']);
    grunt.registerTask('buildcoffee', ['coffee_build']);
    grunt.registerTask('buildless', ['less']);
    grunt.registerTask('buildwatch', ['watch']);
    return grunt.registerTask('default', ['watch']);
  };

}).call(this);
