// Generated by CoffeeScript 1.3.3
(function() {

  exports.index = function(req, res) {
    return res.render("index");
  };

  exports.twocol = function(req, res) {
    return res.render("twocol");
  };

}).call(this);
