// Generated by CoffeeScript 1.6.2
(function() {
  $(function() {
    var back2top;

    back2top = $("div.back2top");
    back2top.addClass("disappear");
    back2top.click(function(event) {
      event.preventDefault();
      return $("html, body").animate({
        scrollTop: 0
      }, 450);
    });
    $("input.checkbox").click(function(event) {
      return $("html, body").animate({
        scrollTop: 0
      }, 450);
    });
    return $(window).scroll(function() {
      var position;

      position = $(this).scrollTop();
      if (position > 200) {
        back2top.removeClass("disappear");
        return back2top.addClass("appear");
      } else if (position <= 200) {
        back2top.removeClass("appear");
        return back2top.addClass("disappear");
      }
    });
  });

}).call(this);
