// Generated by CoffeeScript 1.6.2
(function() {
  var appModule;

  appModule = angular.module('app', []);

  appModule.directive('template', function() {
    return {
      restrict: 'E',
      templateUrl: 'prebuildHeader.html',
      replace: false
    };
  });

}).call(this);
