// Generated by CoffeeScript 1.6.2
(function() {
  var appModule;

  appModule = angular.module('app', []);

  angular.module('test', function() {
    return {
      restrict: 'E',
      template: '<div>TEST HELLO WORLD</div>',
      replate: true
    };
  });

}).call(this);
