// Generated by CoffeeScript 1.6.2
(function() {
  var app;

  app = angular.module('templatingApp', []);

  app.directive('msuHeader', function() {
    return {
      restrict: 'E',
      transclude: true,
      templateUrl: 'templates/prebuildHeader.html',
      replace: false
    };
  });

  app.directive('msuFooter', function() {
    return {
      restrict: 'E',
      transclude: true,
      templateUrl: 'templates/prebuildFooter.html',
      replace: false
    };
  });

}).call(this);
